version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/dream-vacation-backend:latest
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=${RDS_HOST}
      - DB_USER=${RDS_USERNAME}
      - DB_PASSWORD=${RDS_PASSWORD}
      - DB_NAME=${RDS_DATABASE}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    image: ${DOCKERHUB_USERNAME}/dream-vacation-frontend:latest
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s