version: '3.8'

services:
  backend:
    image: wilfred2018/dream-vacation-backend
    container_name: vacation-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - vacation-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: wilfred2018/dream-vacation-frontend
    container_name: vacation-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - vacation-net
    environment:
      - REACT_APP_API_URL=http://backend:3001

networks:
  vacation-net:
    driver: bridge