name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy project files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "rm -rf ~/dream-vacation-app && mkdir -p ~/dream-vacation-app"
          scp -o StrictHostKeyChecking=no -i key.pem -r docker-compose.yml dump.sql ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/dream-vacation-app/

      - name: Deploy and setup on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e  # Exit on error
          cd ~/dream-vacation-app

          echo "Creating .env file..."
          cat <<EOT > .env
DB_HOST=${{ secrets.RDS_HOST }}
DB_USER=${{ secrets.RDS_USERNAME }}
DB_PASSWORD=${{ secrets.RDS_PASSWORD }}
DB_NAME=${{ secrets.RDS_DATABASE }}
EOT

          echo "Installing MySQL client..."
          sudo apt-get update && sudo apt-get install -y mysql-client

          echo "Initializing database..."
          mysql -h ${{ secrets.RDS_HOST }} -u ${{ secrets.RDS_USERNAME }} -p"${{ secrets.RDS_PASSWORD }}" <<MYSQL_SCRIPT
          CREATE DATABASE IF NOT EXISTS ${{ secrets.RDS_DATABASE }};
          USE ${{ secrets.RDS_DATABASE }};
          MYSQL_SCRIPT

          echo "Logging in to DockerHub..."
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          echo "Pulling Docker images..."
          docker-compose pull

          echo "Starting containers..."
          docker-compose down || true
          docker-compose up -d

          echo "Waiting for services to initialize..."
          sleep 30

          echo "Importing database dump..."
          mysql -h ${{ secrets.RDS_HOST }} -u ${{ secrets.RDS_USERNAME }} -p"${{ secrets.RDS_PASSWORD }}" ${{ secrets.RDS_DATABASE }} < dreamvacations.sql

          echo "Verifying database..."
          mysql -h ${{ secrets.RDS_HOST }} -u ${{ secrets.RDS_USERNAME }} -p"${{ secrets.RDS_PASSWORD }}" -e "SHOW TABLES" ${{ secrets.RDS_DATABASE }}

          echo "Deployment completed successfully!"
          EOF