name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with SSH and Docker Compose
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          RDS_HOST: ${{ secrets.RDS_HOST }}
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          RDS_DATABASE: ${{ secrets.RDS_DATABASE }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          # Save SSH key to a file
          echo "$EC2_SSH_KEY" > ssh_key
          chmod 600 ssh_key

          # Copy files to EC2
          scp -i ssh_key -o StrictHostKeyChecking=no docker-compose.yml $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/
          scp -i ssh_key -o StrictHostKeyChecking=no dreamvacations.sql $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/

          # SSH into EC2 and deploy
          ssh -i ssh_key -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST << 'EOF'
            export DEBIAN_FRONTEND=noninteractive

            # Install MySQL Shell
            sudo apt-get update -y
            sudo apt-get install -y mysql-client

            # Connect to RDS with mysql shell, create and use the database
            mysql -h $RDS_HOST -u $RDS_USERNAME -p$RDS_PASSWORD <<EOSQL
CREATE DATABASE $RDS_DATABASE;
USE $RDS_DATABASE;
EXIT;
EOSQL

            # Import SQL dump
            mysql -h $RDS_HOST -u $RDS_USERNAME -p$RDS_PASSWORD $RDS_DATABASE < /home/$EC2_USERNAME/dreamvacations.sql

            # Pull latest images
            docker pull $DOCKERHUB_USERNAME/dream-vacation-backend:latest
            docker pull $DOCKERHUB_USERNAME/dream-vacation-frontend:latest

            # Run docker-compose
            cd /home/$EC2_USERNAME
            docker-compose down
            docker-compose up -d
          EOF

          # Clean up
          rm ssh_key

