name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with SSH and Docker Compose
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          RDS_HOST: ${{ secrets.RDS_HOST }}
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          RDS_DATABASE: ${{ secrets.RDS_DATABASE }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          # Save SSH key to a file
          echo "$EC2_SSH_KEY" > ssh_key
          chmod 600 ssh_key
         
          if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$RDS_DATABASE" ]; then
             echo "Required environment variables are missing. Exiting."
             exit 1
          fi

          # Copy files to EC2
          scp -i ssh_key -o StrictHostKeyChecking=no docker-compose.yml $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/
          scp -i ssh_key -o StrictHostKeyChecking=no dreamvacations.sql $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/

          # SSH into EC2 and deploy
          ssh -i ssh_key -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST << EOF
            set -e  # Exit on error

            # Install MySQL client
            sudo apt-get update -y
            sudo apt-get install -y mysql-client
          

            # Create database if not exists and use it
            mysql -h $RDS_HOST -u $RDS_USERNAME -p$RDS_PASSWORD <<EOSQL
            CREATE DATABASE IF NOT EXISTS $RDS_DATABASE;
            USE $RDS_DATABASE;
          EOSQL
            
            # Check if the database is empty
            if [ \$(mysql -h $RDS_HOST -u $RDS_USERNAME -p$RDS_PASSWORD -e "USE $RDS_DATABASE; SHOW TABLES;" | wc -l) -eq 0 ]; then
              echo "Database is empty, importing SQL dump."
            else
              echo "Database is not empty, skipping import."
            fi            
            
            # Pull latest images from DockerHub
            docker pull $DOCKERHUB_USERNAME/dream-vacation-backend:latest
            docker pull $DOCKERHUB_USERNAME/dream-vacation-frontend:latest

            # Navigate and deploy
            cd /home/$EC2_USERNAME
            docker-compose down
            docker-compose up -d
          EOF

          # Clean up
          rm ssh_key